#!/usr/bin/env python3
"""
Create .mjv (Motion JPEG Video) files for the vib-OS video player.

.mjv container format (all integers little-endian):
  Offset  Size  Field
  0       4     Magic "MJV1"
  4       4     Width (pixels)
  8       4     Height (pixels)
  12      4     FPS
  16      4     Frame count N
  20      8*N   Frame table: for each frame, u32 offset (from file start)
                followed by u32 size in bytes
  ...           Concatenated baseline JPEG frames

Frames must be baseline sequential JPEG (no progressive, no EXIF,
4:4:4 or 4:2:0 subsampling) so the kernel's picojpeg decoder accepts them.

Usage:
  create_mjv.py sample                 Generate the procedural sample video
                                       and bootstrap_video_mjv.c
  create_mjv.py pack out.mjv fps f1.jpg f2.jpg ...
                                       Pack existing baseline JPEGs
"""
import io
import math
import struct
import sys

from PIL import Image, ImageDraw

MAGIC = b"MJV1"


def encode_frame(img):
    """Encode a PIL image as a picojpeg-compatible baseline JPEG."""
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=75, optimize=False, progressive=False,
             subsampling=0, exif=b"")
    return buf.getvalue()


def write_mjv(path, frames, width, height, fps):
    header_size = 20 + 8 * len(frames)
    offsets = []
    pos = header_size
    for f in frames:
        offsets.append(pos)
        pos += len(f)

    with open(path, "wb") as out:
        out.write(MAGIC)
        out.write(struct.pack("<IIII", width, height, fps, len(frames)))
        for off, f in zip(offsets, frames):
            out.write(struct.pack("<II", off, len(f)))
        for f in frames:
            out.write(f)
    print(f"{path}: {len(frames)} frames {width}x{height} @{fps}fps, "
          f"{pos} bytes")


def make_sample_frame(w, h, t):
    """One frame of the sample video: moving sky gradient, sun sweep,
    bouncing ball, frame counter bar."""
    img = Image.new("RGB", (w, h))
    px = img.load()

    # Sky gradient that slowly shifts hue over time
    shift = 0.5 + 0.5 * math.sin(2 * math.pi * t)
    for y in range(h):
        ratio = y / h
        r = int(30 + 60 * ratio + 40 * shift)
        g = int(60 + 80 * ratio)
        b = int(140 + 80 * ratio - 40 * shift)
        for x in range(w):
            px[x, y] = (r, g, b)

    draw = ImageDraw.Draw(img)

    # Sun sweeping left to right along an arc
    sun_x = int(w * t)
    sun_y = int(h * 0.35 - h * 0.2 * math.sin(math.pi * t))
    draw.ellipse([sun_x - 18, sun_y - 18, sun_x + 18, sun_y + 18],
                 fill=(255, 220, 80))

    # Ground
    draw.rectangle([0, int(h * 0.8), w, h], fill=(40, 120, 50))

    # Bouncing ball
    ball_x = int(w * 0.15 + w * 0.7 * t)
    bounce = abs(math.sin(3 * math.pi * t))
    ball_y = int(h * 0.78 - h * 0.35 * bounce)
    draw.ellipse([ball_x - 12, ball_y - 12, ball_x + 12, ball_y + 12],
                 fill=(230, 60, 60))

    # Progress bar so frame advance is obvious in screenshots
    draw.rectangle([0, h - 8, int(w * t), h], fill=(255, 255, 255))
    return img


def emit_c_array(mjv_path, c_path, symbol):
    with open(mjv_path, "rb") as f:
        data = f.read()
    with open(c_path, "w") as out:
        out.write("/* Auto-generated by create_mjv.py - do not edit.\n"
                  " * Sample .mjv video seeded into the ramfs at boot. */\n\n")
        out.write(f"const unsigned char {symbol}[] = {{\n")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
            out.write(f"    {chunk},\n")
        out.write("};\n")
        out.write(f"const unsigned int {symbol}_len = {len(data)};\n")
    print(f"{c_path}: {len(data)} bytes as {symbol}[]")


def cmd_sample():
    w, h, fps, seconds = 320, 240, 12, 5
    n = fps * seconds
    frames = [encode_frame(make_sample_frame(w, h, i / (n - 1)))
              for i in range(n)]
    write_mjv("bootstrap_images/sample.mjv", frames, w, h, fps)
    emit_c_array("bootstrap_images/sample.mjv", "bootstrap_video_mjv.c",
                 "bootstrap_video_mjv")


def cmd_pack(argv):
    out_path, fps = argv[0], int(argv[1])
    frames = []
    size = None
    for p in argv[2:]:
        img = Image.open(p).convert("RGB")
        if size is None:
            size = img.size
        elif img.size != size:
            img = img.resize(size)
        frames.append(encode_frame(img))
    write_mjv(out_path, frames, size[0], size[1], fps)


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "sample":
        cmd_sample()
    elif len(sys.argv) >= 5 and sys.argv[1] == "pack":
        cmd_pack(sys.argv[2:])
    else:
        print(__doc__)
        sys.exit(1)
